site_name: Root Notebook

site_description: www

site_url: https://guang1234567.github.io/MyNotebook

repo_url: https://github.com/Guang1234567/MyNotebook

edit_uri: edit/master/markdown/docs/

markdown_extensions:
  - admonition
  - smarty
  - sane_lists
  - mdx_math
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML'

extra_css:
  - css/style.css
  - css/admonition_fix.css
  - css/pymdownx_tasklist_custom.css
  - css/mkdocs_recipes.css

docs_dir: 'docs'

#theme: yeti

theme:
  name: yeti
  custom_dir: custom_theme

pages:
  - 主页: 'index.md'
  - 关于: 'about.md'
  - 样式指南: 'styleguide.md'
  - 专有词汇翻译记录: 'glossary.md'
  - 目录:
    - 简介: 'intro.md'
    - 入门:
      - OpenGL: '01 Getting started/01 OpenGL.md'
      - 创建窗口: '01 Getting started/02 Creating a window.md'
      - 你好，窗口: '01 Getting started/03 Hello Window.md'
      - 你好，三角形: '01 Getting started/04 Hello Triangle.md'
      - 着色器: '01 Getting started/05 Shaders.md'
      - 纹理: '01 Getting started/06 Textures.md'
      - 变换: '01 Getting started/07 Transformations.md'
      - 坐标系统: '01 Getting started/08 Coordinate Systems.md'
      - 摄像机: '01 Getting started/09 Camera.md'
      - 复习: '01 Getting started/10 Review.md'
    - 光照:
      - 颜色: '02 Lighting/01 Colors.md'
      - 基础光照: '02 Lighting/02 Basic Lighting.md'
      - 材质: '02 Lighting/03 Materials.md'
      - 光照贴图: '02 Lighting/04 Lighting maps.md'
      - 投光物: '02 Lighting/05 Light casters.md'
      - 多光源: '02 Lighting/06 Multiple lights.md'
      - 复习: '02 Lighting/07 Review.md'
